### ISSUE TITLE
Create Repo

### ISSUE THREAD

**Issue by repository-creation-bot-user** [repository-creation-bot/repository-self-service#8]
Fill out the request form by replacing the values below with your requested values. 
This template will be parsed by our automatic repo creation bot.
Keep the structure as it is otherwise the bot will not work.

### Repository Name

team02-module02

### Template Repository

team02-module01

**Comment by Danielku15** [comment]
[repo-bot] This is the information I understood: 
```
Parsed Repository Name: 'team02-module02'
Sanitized Repository Name: 'team-0-2-module-0-2'
Parsed Template Repository: 'team02-module01'
Resolved Template Repository: 'team02-module01'
Issue Author is Template Admin: 'false'
Common Prefix: 'undefined'
Issue Author can approve: 'false'
```
 ✅ The information about the repository is looks good. But as you are not an admin of the template repository, either a repository or organization admin needs to approve your request. 
    You can either ask any repository or organization admin to approve your request by commenting `/repo-bot approve` or comment `/repo-bot ping-admins` to ping the organization administrators.

**Comment by Danielku15** [comment]
[repo-bot] Sorry but it seems you are not having the required permissions to approve the repository creation 😞.
      Please reach out to one of the administrators of the `team02-module01` to approve this request, or
      use `/repo-admin ping-admins` to ping the organization admins for approval. You might want to reach out to them also separately 
      depending on how urgent and long-running this repository creation might be.

**Comment by Danielku15** [comment]
[repo-bot] Hey @repository-creation-bot/org-admins 👋! It seems repository-creation-bot-user is either facing troubles or needs your approval for this request.

**Comment by Danielku15** [comment]
[repo-bot] Great, got some work to do 💪! I will start now creation of your repository, this might take a while until it is completed. 
    I will close this issue once the repository was created.

**Comment by Danielku15** [comment]
[repo-bot] 🥳🎉 The repository creation completed without errors. You can now access the repository at https://github.com/repository-creation-bot/team-0-2-module-0-2. Happy coding. I will close this issue now.
